name: Print Hello World

on:
  schedule:
    - cron: '* * * * *'  # Runs every minute

jobs:
  print-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello World"
