name: Databricks Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy-to-dev:
    runs-on: self-hosted
    steps:
      # Step 1: Check if Databricks CLI is installed
      - name: Check if Databricks CLI is installed
        id: check-databricks-cli
        run: |
          if ! command -v databricks &> /dev/null; then
            echo "Databricks CLI not found. Installing Databricks CLI..."
            echo "cli_installed=false" >> $GITHUB_ENV
          else
            echo "Databricks CLI is already installed."
            echo "cli_installed=true" >> $GITHUB_ENV
          fi

      # Step 2: Install Databricks CLI if not installed
      - name: Install Databricks CLI
        if: env.cli_installed == 'false'
        run: |
          echo "Installing Databricks CLI..."
          pip install databricks-cli
          databricks --version
          echo "Databricks CLI has been installed successfully."

      # Step 3: Authenticate Dev Databricks Workspace
      - name: Authenticate Dev Databricks Workspace
        run: |
          mkdir -p ~/.databricks
          cat <<EOF > ~/.databrickscfg
          [DEFAULT]
          host = "${{ vars.QA_DATABRICKS_HOST }}"
          token = "${{ secrets.QA_DATABRICKS_TOKEN }}"
          EOF
          chmod 600 ~/.databrickscfg
          databricks auth profiles

      # Step 4: Download Files from Remote Repository
      - name: Download Files from Remote Repository
        run: |
          if [ -d "Databricks_Notebooks" ]; then
            echo "Folder exists. Pulling latest changes..."
            cd Databricks_Notebooks
            git pull origin main
            cd ..
          else
            echo "Folder does not exist. Cloning the repository..."
            git clone --branch main "${{ vars.repo_url }}" Databricks_Notebooks
          fi

      # Step 5: Synchronize Local Folder with Dev Databricks Workspace
      - name: Synchronize Local Folder with Dev Databricks Workspace
        run: |
          cd Databricks_Notebooks
          databricks sync Notebooks /Workspace/Shared/
          echo "Notebooks deployed to Dev Databricks Workspace."

  
