name: Databricks Deployment
 
on:
  push:
    branches:
      - main
 
jobs:
  pre-deployment-approval:
    runs-on: self-hosted
    environment: pre-deployment-approval
    steps:
      - name: Request Pre-Deployment Approval
        run: echo "Pre-deployment approval requested. Waiting for approver to approve."
 
  deploy-to-dev:
    needs: pre-deployment-approval
    runs-on: self-hosted
    if: github.ref == 'refs/heads/main'
    steps:
      # Step 1: Check if Databricks CLI is installed
      - name: Check if Databricks CLI is installed
        run: |
          if (-not (Get-Command databricks -ErrorAction SilentlyContinue)) {
            Write-Host "Databricks CLI not found. Please install the Databricks CLI on the runner."
          } else {
            Write-Host "Databricks CLI is already installed."
          }
 
      # Step 2: Authenticate Dev Databricks Workspace
      - name: Authenticate Dev Databricks Workspace
        run: |
          New-Item -ItemType Directory -Force -Path $env:USERPROFILE\.databricks
          @"
          [DEFAULT]
          host = "${{ vars.QA_DATABRICKS_HOST }}"
          client_id = "${{ secrets.QA_DATABRICKS_CLIENT_ID }}"
          client_secret = "${{ secrets.QA_DATABRICKS_CLIENT_SECRET }}"
          "@ | Out-File -FilePath "$env:USERPROFILE\.databrickscfg" -Encoding utf8
          icacls "$env:USERPROFILE\.databrickscfg" /inheritance:r /grant:r "$env:USERNAME`:F"
          databricks auth profiles
 
      # Step 3: Download Files from Remote Repository to Local Workspace
      - name: Download the Files from Remote repo to Local workspace
        run: |
          if (Test-Path "QA") {
            Write-Host "Folder exists. Pulling latest changes..."
            Set-Location QA
            Set-Location AVA-DATABRICKS-QMC-POC
            git pull origin main
            Set-Location ..
            Set-Location ..
          } else {
            Write-Host "Folder does not exist. Creating 'QA' folder and cloning the repository..."
            New-Item -ItemType Directory -Path "QA"  # Create the 'QA' folder
            Set-Location QA
            git clone --branch main "${{ vars.REPO_PAT }}" AVA-DATABRICKS-QMC-POC  # Clone into the 'AVA-DATABRICKS-QMC-POC' subfolder
            Set-Location ..
          }
 
      # Step 4: Synchronize Local Folder with Databricks
      - name: Synchronize Local folder with databricks
        run: |
          cd QA
          cd AVA-DATABRICKS-QMC-POC
          databricks sync Notebooks /Workspace/Shared
 
  post-deployment-approval:
    needs: deploy-to-dev
    runs-on: self-hosted
    environment: post-deployment-approval
    steps:
      # Step 1: Simulate Manual Approval with Inputs
      - name: Simulate Post-Deployment Approval
        id: post-deployment-approval
        run: |
          echo "Post-deployment approval requested. Waiting for QA approver to approve."
          echo "Choose an action: Approve or Reject"
          # Simulate user input (Replace with actual manual approval mechanism)
          APPROVAL_ACTION="Reject"  # Replace with dynamic input (e.g., from workflow_dispatch)
          echo "Selected action: $APPROVAL_ACTION"
          echo "action=$APPROVAL_ACTION" >> $GITHUB_ENV

      # Step 2: Revert to Previous Commit if Rejected
      - name: Revert to Previous Commit
        if: env.action == 'Reject'
        run: |
          echo "Reverting deployment to previous commit..."
          git fetch --depth=100  # Fetch more commits to access the previous commit
          PREVIOUS_COMMIT_ID=$(git rev-parse HEAD^)  # Get the previous commit ID
          echo "Previous commit ID: $PREVIOUS_COMMIT_ID"
          git checkout $PREVIOUS_COMMIT_ID  # Checkout the previous commit

      # Step 3: Redeploy Application
      - name: Redeploy Application
        if: env.action == 'Reject'
        run: |
          echo "Redeploying application from commit: ${{ env.PREVIOUS_COMMIT_ID }}"
          cd QA
          cd AVA-DATABRICKS-QMC-POC
          databricks sync Notebooks /Workspace/Shared
          echo "Deployment reverted successfully."

      # Step 4: Confirm Approval
      - name: Confirm Approval
        if: env.action == 'Approve'
        run: |
          echo "Deployment approved. No further action required."
