name: Hello World Every 15 Minutes

on:
  schedule:
    # Runs every 15 minutes (see https://crontab.guru/#*/15_*_*_*_*) 
    - cron: '*/15 * * * *'
  # Allows manual trigger for testing
  workflow_dispatch:

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello World
        run: |
          echo "Hello World"
