name: Post-Deployment Approval and Rollback

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Choose action"
        required: true
        type: choice
        options:
          - Approve
          - Reject

jobs:
  Roll-back-setup:
    runs-on: self-hosted
 

    steps:
      # Step 1: Conert the input to variable
      - name: Simulate Post-Deployment Approval
        id: post-deployment-approval
        run: |
          echo "Post-deployment approval requested. Waiting for QA approver to approve."
          echo "Selected action: ${{ github.event.inputs.action }}"
          echo "action=${{ github.event.inputs.action }}" >> $GITHUB_ENV

      # Step 2: Revert to Previous Commit if Rejected
      - name: Revert to Previous Commit
        if: env.action == 'Reject'
        run: |
          echo "Reverting deployment to previous commit..."
          PREVIOUS_COMMIT_ID=$(git rev-parse HEAD^)  # Get the previous commit ID
          echo "Previous commit ID: $PREVIOUS_COMMIT_ID"
          git checkout $PREVIOUS_COMMIT_ID  # Checkout the previous commit
          echo "Checked out commit: $PREVIOUS_COMMIT_ID"

      # Step 3: Redeploy Application
      - name: Redeploy Application
        if: env.action == 'Reject'
        run: |
          echo "Redeploying application from commit: ${{ env.PREVIOUS_COMMIT_ID }}"
          cd QA
          cd AVA-DATABRICKS-QMC-POC
          databricks sync Notebooks /Workspace/Shared
          echo "Deployment reverted successfully."

      # Step 4: Confirm Approval
      - name: Confirm Approval
        if: env.action == 'Approve'
        run: |
          echo "Deployment approved. No further action required."
